services:
  gtnh:
    build:
      dockerfile: amazon.dockerfile
      context: .
      args:
        - GTNH_VERSION=${GTNH_VERSION}
    container_name: GregTechNewHorizons
    image: gtnh:amazon-${GTNH_VERSION}
    init: true
    stdin_open: true
    tty: true
    user: "minecraft:minecraft"
    volumes:
      - ${PWD}/crash-reports:/app/crash-reports
      - ${PWD}/heapdumps:/app/heapdumps
      - ${PWD}/logs:/app/logs
      - ${PWD}/world:/app/world
      - ${PWD}/backups:/app/backups
    ports:
      - "22000:25565"
      - "9001:9001"
