version: "3.8"
services:
  gtnh:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - GTNH_VERSION=${GTNH_VERSION}
    container_name: GregTechNewHorizons
    image: officepi:5000/gtnh:${GTNH_VERSION}
    init: true
    stdin_open: true
    tty: true
    user: "minecraft:minecraft"
    volumes:
      - ${PWD}/server.properties:/app/server.properties
      - ${PWD}/whitelist.json:/app/whitelist.json
      - ${PWD}/usercache.json:/app/usercache.json
      - ${PWD}/ops.json:/app/ops.json
      - ${PWD}/banned-players.json:/app/banned-players.json
      - ${PWD}/crash-reports:/app/crash-reports
      - ${PWD}/heapdumps:/app/heapdumps
      - ${PWD}/logs:/app/logs
      - ${PWD}/world:/app/world
      - ${PWD}/backups:/app/backups
      - ${PWD}/serverutilities.cfg:/app/serverutilities/serverutilities.cfg
    ports:
      - "22000:25565"
